# Site settings
title:       Michael Wu
email:       wujianfei871015@gmail.com
author:      Michael
description: "I am geared to learning more about cloud computing."
baseurl:     ""
url:         "http://wujianfeionline.com"

# Google analytics
google_analytics: UA-57186197-1

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false

# Social icons
show_social_icons: true
github_username: yellowmamba
twitter_username: wujianfei
linkedin_username: wujianfei

# Build settings
markdown:     kramdown
permalink:    /posts/:title/
paginate:     5 
sass:
  compressed: true

gems:
  - jekyll-sitemap

date_format: "%Y-%m-%d"