# Site settings
title:       Jianfei Wu
email:       wujianfei871015@gmail.com
author:      Michael
description: ""
baseurl:     ""
url:         ""

# Google analytics
google_analytics:

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false

# Social icons
show_social_icons: true
github_username: yellowmamba
twitter_username: wujianfei
linkedin_username: wujianfei

# Build settings
markdown:     kramdown
permalink:    pretty
paginate:     5
sass:
  compressed: true
